### ISSUE TITLE
Drawing board not loading

### ISSUE THREAD

**Issue by Mr-Pepe** [gugray/hanzi_lookup#1]
If I open index.html, the drawing board only shows "Loading...". Is there anything I have to do? It looks to me like jQuery is already included in index.html.

**Comment by zmyjiekema** [comment]
> 如果我打开 index.html，绘图板只显示“正在加载...”。有什么我必须做的吗？在我看来 jQuery 已经包含在 index.html 中。
Open it as a service, such as http-server
